using System;
using System.Data;
using AccosoftUtilities;
using AccosoftLogWriter;
using AccosoftNineteenCDL;
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;
using System.Collections;
using System.Collections.Generic;
using Newtonsoft.Json;

/// <summary>
/// Summary description for RMWeighbridgeTokenEntryLogic
/// </summary>
/// 

namespace AccosoftRML.Busiess_Logic.RawMaterial
{
    public class RMWeighbridgeTokenEntryLogic
    {


        static string sConString = Utilities.cnnstr;
        //   string scon = sConString;

        OracleConnection ocConn = new OracleConnection(sConString.ToString());


        //  OracleConnection ocConn = new OracleConnection(System.Configuration.ConfigurationManager.ConnectionStrings["accoSoftConnection"].ToString());
        ArrayList SQLArray = new ArrayList();
        String SQL = string.Empty;

        public RMWeighbridgeTokenEntryLogic ( )
        {
            //
            // TODO: Add constructor logic here
            //
        }



        #region "DML statement"


        public string GetDocumnentNo ( string stCode, string sFromCode, int iFinYearId )
        {
            DataTable dtCode = new DataTable();
            try
            {


                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = "SELECT AD_DN_NEXT_NO FROM AD_DOC_NUMBER_STATION WHERE SALES_STN_STATION_CODE ='" + stCode + "' AND  AD_MI_ITEMID='" + sFromCode + "' AND AD_FIN_FINYRID=" + iFinYearId + "";

                dtCode = clsSQLHelper.GetDataTableByCommand(SQL);


            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return System.Convert.ToString(dtCode.Rows[0].ItemArray[0]);
        }

        public string InsertSql ( RMWeighbridgeTokenEntryEntity oEntity,string sDocNo,  object mngrclassobj, bool bDocAutogenerated)
        {
            string sRetun = string.Empty;
            //int nRecordsAffected = 0; 
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                SQLArray.Clear(); 

                SQL = "INSERT INTO RM_RECEPIT_TOKEN_MST ( ";
                SQL = SQL + "   RM_RT_TOKEN_NO, AD_FIN_FINYRID, RM_RT_TOKEN_DATE,AD_BR_CODE,SALES_STN_STATION_CODE,  ";
                SQL = SQL + "   RM_RT_TOKEN_DATE_TIME, RM_VM_VENDOR_CODE, FA_FAM_ASSET_CODE,  ";
                SQL = SQL + "   RM_RT_VEHICLE_DESCRIPTION, RM_RT_DRIVER_CODE, RM_RT_DRIVER_NAME,  ";
                SQL = SQL + "   RM_RMM_RM_CODE,  "; 
                SQL = SQL + "   RM_RT_CREATEDBY, RM_RT_CREATEDDATE)  ";
                SQL = SQL + "VALUES ('"+oEntity.TokenNo+"','"+mngrclass.FinYearID+"','" + oEntity.TokenDate.ToString("dd-MMM-yyyy") + "' ,'"+oEntity.BranchCode+"','"+oEntity.StationCode+"',  ";
                SQL = SQL + "TO_DATE('" + Convert.ToDateTime(oEntity.TokenTime).ToString("dd-MMM-yyyy hh:mm:ss tt") + "','DD-MM-YYYY HH:MI:SS AM'),'"+oEntity.VendorCode+"','"+oEntity.TruckCode+"' , ";
                SQL = SQL + "'"+oEntity.TruckName+"','"+oEntity.DriverCode+"','"+oEntity.DriverName+"' ,";
                SQL = SQL + "'"+oEntity.RMCode + "',  ";
                SQL = SQL + "'"+oEntity.CreatedBy+"', '" + oEntity.TokenDate.ToString("dd-MMM-yyyy") + "' ";
                SQL = SQL + ")";

                SQLArray.Add(SQL);  

                 SQLArray.Add(ResSetNextDocNumberStation("RTWBT", sDocNo,mngrclass.FinYearID, oEntity.StationCode));

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RTWBT",oEntity.TokenNo, false, Environment.MachineName, "I", SQLArray);
            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }

        public string UpdateSQL ( RMWeighbridgeTokenEntryEntity oEntity, object mngrclassobj)
        {
            string sRetun = string.Empty;
            DataTable dtSEQ = new DataTable();
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                SQLArray.Clear();

                SQL = "UPDATE RM_RECEPIT_TOKEN_MST SET  FA_FAM_ASSET_CODE='"+oEntity.TruckCode+"',  ";
                SQL = SQL + "                           RM_VM_VENDOR_CODE='" + oEntity.VendorCode+"',  ";
                SQL = SQL + "                           RM_RT_VEHICLE_DESCRIPTION='"+oEntity.TruckName+"',  ";
                SQL = SQL + "                           RM_RT_DRIVER_CODE='"+oEntity.DriverCode+"',  ";
                SQL = SQL + "                           RM_RT_DRIVER_NAME='"+oEntity.DriverName+"',  ";
                SQL = SQL + "                           RM_RT_UPDATEDBY='"+mngrclass.UserName+"',  ";
                SQL = SQL + "                            RM_RMM_RM_CODE='" + oEntity.RMCode + "',   ";
                SQL = SQL + "                           RM_RT_UPDATEDDATE='" +DateTime.Now.ToString("dd-MMM-yyyy") + "'  ";
                SQL = SQL + "                     WHERE RM_RT_TOKEN_NO='"+oEntity.TokenNo+"' ";
                SQL = SQL + "                       AND RM_RT_STATUS='O'  ";


                SQLArray.Add(SQL);


                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RTWBT",oEntity.TokenNo, false, Environment.MachineName, "U", SQLArray);
            }


            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;

        }
         
        public string DeleteSQL ( String sCode, object mngrclassobj )
        {
            string sRetun = string.Empty;
            try
            {

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                OracleHelper oTrns = new OracleHelper();


                ////NEEED TO ADD DELETE CHECK   RECEIPT ENTRY
                sRetun = DeleteCheckReceiptDetails(sCode);

                if (sRetun != "CONTINUE")
                {
                    return sRetun;
                }


                 SQL = "DELETE FROM RM_RECEPIT_TOKEN_MST WHERE RM_RT_TOKEN_NO='"+sCode+"' ";

                SQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RTWBT", sCode, false, Environment.MachineName, "D", SQLArray);

            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;

        }

        public string REQClose ( string TokenNo, object mngrclassobj )
        {

            string sRetun = string.Empty;
            // string sApprStatus = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();
                SessionManager mngrclass = (SessionManager)mngrclassobj;

                SQLArray.Clear();

                SQL = "update RM_RECEPIT_TOKEN_MST set RM_RT_STATUS='C' where RM_RT_TOKEN_NO='"+TokenNo+"' ";
                SQLArray.Add(SQL);

                sRetun = string.Empty;

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RTWBT",TokenNo,  false, Environment.MachineName, "U", SQLArray);

            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);

                return sRetun;
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }

        public string REQOpen ( string TokenNo, object mngrclassobj )
        {

            string sRetun = string.Empty;
            // string sApprStatus = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();
                SessionManager mngrclass = (SessionManager)mngrclassobj;

                SQLArray.Clear();

                 sRetun = DeleteCheckReceiptDetails(TokenNo);

                if (sRetun != "CONTINUE")
                {
                    return sRetun;
                }


                SQL = "update RM_RECEPIT_TOKEN_MST set RM_RT_STATUS='O' where RM_RT_TOKEN_NO='"+TokenNo+"' ";
                SQLArray.Add(SQL);

                sRetun = string.Empty;

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RTWBT",TokenNo,  false, Environment.MachineName, "U", SQLArray);

            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);

                return sRetun;
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }
          
        public string ResSetNextDocNumberStation(String FormCode, String CurrentNumber, int iFinYearId, String stCode)
        {

            int liLength = 0;
            String lsCode = string.Empty;
            int liZeros = 0;
            int liNumber = 0;
            int i = 0;

            String lsResult = string.Empty;

            lsCode = CurrentNumber;
            liLength = lsCode.Length;

            liNumber = int.Parse(lsCode) + 1;
            liZeros = liLength - liNumber.ToString().Length;

            for (i = 1; i <= liZeros; i++)
            {
                lsResult = lsResult + "0";
            }

            lsResult = lsResult + liNumber;

            return "UPDATE  AD_DOC_NUMBER_STATION SET AD_DN_NEXT_NO='" + lsResult + "' WHERE AD_MI_ITEMID='" + FormCode + "' AND AD_FIN_FINYRID=" + iFinYearId + " and SALES_STN_STATION_CODE ='" + stCode + "'";

        }

        private string DeleteCheckReceiptDetails(string txtEntryNo)
        {
            DataSet dsCnt = new DataSet();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();
                 
                SQL = " select count(*)CNT from RM_RECEIPT_MASTER where RM_RT_TOKEN_NO='" + txtEntryNo + "'";

                dsCnt = clsSQLHelper.GetDataset(SQL);

                if (System.Convert.ToInt16(dsCnt.Tables[0].Rows[0].ItemArray[0]) > 0)
                {
                    return "Receipt details already Created";
                }

            }
            catch (Exception ex)
            {
                return System.Convert.ToString(ex.Message);
            }
            return "CONTINUE";
        }

        #endregion
         

        #region "print"

        public DataSet FetchDataPrint ( string TokenNo )
        {
            DataSet dsData = new DataSet();

            try
            {

                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = "SELECT      ";
                SQL = SQL + " RM_RT_TOKEN_NO,AD_FIN_FINYRID,     ";
                SQL = SQL + "  RM_RT_TOKEN_DATE,RM_RT_TOKEN_DATE_TIME,     ";
                SQL = SQL + "   RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE,CASE WHEN RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE='16' THEN 'OTHER ITEMS' ELSE  RM_RMM_RM_DESCRIPTION  END AS RM_DESCRIPTION, ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE,RM_VM_VENDOR_NAME,     ";
                SQL = SQL + "  FA_FAM_ASSET_CODE,RM_RT_VEHICLE_DESCRIPTION,     ";
                SQL = SQL + "  RM_RT_DRIVER_CODE,RM_RT_DRIVER_NAME,RM_RT_CREATEDBY,RM_RT_CREATEDDATE,RM_RT_UPDATEDBY,     ";
                SQL = SQL + "  RM_RT_UPDATEDDATE,RM_MRM_RECEIPT_NO,RM_MRM_FINYRID,DECODE(RM_RT_STATUS, 'O', 'OPEN', 'CLOSE') RM_RT_STATUS,   ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.AD_BR_CODE,AD_BR_NAME,RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE,SALES_STN_STATION_NAME         ";
                SQL = SQL + "  FROM       ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST,rm_vendor_master,sl_station_master,AD_BRANCH_MASTER ,RM_RAWMATERIAL_MASTER     ";
                SQL = SQL + "  WHERE RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE=rm_vendor_master.RM_VM_VENDOR_CODE     ";
                SQL = SQL + "   AND RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE=RM_RAWMATERIAL_MASTER.RM_RMM_RM_CODE(+) ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE=sl_station_master.SALES_STN_STATION_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.AD_BR_CODE=AD_BRANCH_MASTER.AD_BR_CODE     ";
                SQL = SQL + " and RM_RT_TOKEN_NO='" + TokenNo + "'    ";

                DataTable dtMain = new DataTable();
                // DataTable dtDetail = new DataTable();

                // SQL = "select sysdate from dual";

                dtMain = clsSQLHelper.GetDataTableByCommand(SQL);

                dsData.Tables.Add(dtMain);


            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
                return null;
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();

            }
            return dsData;
        }

        #endregion

        #region FillProductDataList

        
        public string FillViewStationDropdown(string UserName)
        {
            string jsonString = "";
            DataTable dtReturn = new DataTable();
            try
            {

                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();


                SQL = " SELECT   SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_CODE, SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_NAME, ";
                SQL = SQL + "  SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_CODE CODE  , SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_NAME NAME  , ";
                SQL = SQL + "  SL_STATION_BRANCH_MAPP_DTLS_VW.GL_COSM_ACCOUNT_CODE  ";
                SQL = SQL + " FROM ";
                SQL = SQL + "   SL_STATION_BRANCH_MAPP_DTLS_VW WHERE   ";
                SQL = SQL + "    SALES_STATION_BRANCH_STATUS_AI ='A' and SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_RAW_MATERIAL_STATION ='Y'    "; 
                  
                if (UserName != "ADMIN")
                {
                    SQL = SQL + "   AND SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_CODE in (select AD_BR_CODE from  ";
                    SQL = SQL + "  AD_USER_GRANTED_BRANCH where AD_UM_USERID = '" + UserName + "')   ";
                }

                if (UserName != "ADMIN")
                {
                    SQL = SQL + "  AND SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_CODE IN ( SELECT     SALES_STN_STATION_CODE FROM ";
                    SQL = SQL + "     WS_GRANTED_STATION_USERS WHERE    AD_UM_USERID   ='" + UserName + "') ";
                }

                SQL = SQL + "  ORDER BY   SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_NAME     ASC  ";




                dtReturn = clsSQLHelper.GetDataTableByCommand(SQL);

                jsonString = JsonConvert.SerializeObject(dtReturn);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return jsonString;

        }
         
        public string FillRMWeighbridgeTokenDataList ( RMWeighbridgeTokenEntry data)
        {
            DataSet dsReturn = new DataSet("RM_RECEPIT_TOKEN");
            DataTable dtMaster = new DataTable();
            string JSONString = string.Empty;
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = "SELECT  ";
                SQL = SQL + " RM_RT_TOKEN_NO,AD_FIN_FINYRID, ";
                SQL = SQL + "  RM_RT_TOKEN_DATE,RM_RT_TOKEN_DATE_TIME, ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE,RM_VM_VENDOR_NAME, ";
                SQL = SQL + "   RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE,CASE WHEN RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE='16' THEN 'OTHER ITEMS' ELSE  RM_RMM_RM_DESCRIPTION  END AS RM_DESCRIPTION, ";
                SQL = SQL + "  FA_FAM_ASSET_CODE,RM_RT_VEHICLE_DESCRIPTION, ";
                SQL = SQL + "  RM_RT_DRIVER_CODE,RM_RT_DRIVER_NAME,RM_RT_CREATEDBY,RM_RT_CREATEDDATE,RM_RT_UPDATEDBY, ";
                SQL = SQL + "  RM_RT_UPDATEDDATE,RM_MRM_RECEIPT_NO,RM_MRM_FINYRID,DECODE(RM_RT_STATUS, 'O', 'OPEN', 'CLOSE') RM_RT_STATUS,   ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.AD_BR_CODE,AD_BR_NAME,RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE,SALES_STN_STATION_NAME         ";
                SQL = SQL + "  FROM       ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST,rm_vendor_master,sl_station_master,AD_BRANCH_MASTER ,RM_RAWMATERIAL_MASTER     ";
                SQL = SQL + "  WHERE RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE=rm_vendor_master.RM_VM_VENDOR_CODE     ";
                SQL = SQL + "   AND RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE=RM_RAWMATERIAL_MASTER.RM_RMM_RM_CODE (+) ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE=sl_station_master.SALES_STN_STATION_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.AD_BR_CODE=AD_BRANCH_MASTER.AD_BR_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE='"+data.Station+"'     ";

                if (!string.IsNullOrEmpty(data.ProductAppStatus))
                {
                    if (data.ProductAppStatus == "WAITING")
                    {
                        SQL = SQL + "AND RM_RT_STATUS='O'";
                    }
                     else if (data.ProductAppStatus == "PROGRESS")
                    {
                        SQL = SQL + "AND RM_RT_STATUS='P'";
                    }
                    else if (data.ProductAppStatus == "CLOSED")
                    { 
                        SQL = SQL + " and RM_RT_TOKEN_DATE between '" + Convert.ToDateTime(data.fromdate).ToString("dd-MMM-yyyy") + "' AND '" + Convert.ToDateTime(data.todate).ToString("dd-MMM-yyyy") + "'  ";

                        SQL = SQL + "AND RM_RT_STATUS='C'";
                    }
                }
                SQL = SQL + " ORDER BY RM_RT_TOKEN_NO ";

                dtMaster = clsSQLHelper.GetDataTableByCommand(SQL);
                dsReturn.Tables.Add(dtMaster);
                dsReturn.Tables[0].TableName = "RM_RECEPIT_TOKEN_MST";

                JSONString = JsonConvert.SerializeObject(dsReturn, Formatting.None);
            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return JSONString;
        }

        public DataTable FillSupplier(string Division)
        {
            DataTable dtData = new DataTable();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                 SQL = " SELECT RM_VENDOR_MASTER.RM_VM_VENDOR_CODE CODE, RM_VENDOR_MASTER.RM_VM_VENDOR_NAME NAME,  ";
                SQL = SQL + "   '' PartNo  ,''RM_UM_UOM_CODE ,  '' RM_UM_UOM_DESC,  ";
                SQL = SQL + " PAY_TERMS_ID  RM_VM_CREDIT_TERMS, SALES_PAY_TYPE_DESC ";
                SQL = SQL + " FROM RM_VENDOR_MASTER, ";// SL_PAY_TYPE_MASTER,  ";
                SQL = SQL + "(  select ";
                SQL = SQL + "    RM_VM_VENDOR_CODE ,  AD_BR_CODE , ";
                SQL = SQL + "    SALES_PAY_TYPE_CODE ,  SALES_PAY_TYPE_DESC , ";
                SQL = SQL + "    RM_VM_LABLE_VALUE PAY_TERMS_ID , ";
                SQL = SQL + "    SALES_PAY_NO_DAYS   rm_vm_credit_period ,RM_VM_LABLE_ID ";
                SQL = SQL + "    from rm_vendor_master_BRANCH_DATA   ,  ";
                SQL = SQL + "    SL_PAY_TYPE_MASTER  ";
                SQL = SQL + "    where RM_VM_LABLE_ID ='PAYMENT_TERMS'  ";
                SQL = SQL + "    and AD_BR_CODE='" + Division + "' ";
                SQL = SQL + "    AND  rm_vendor_master_BRANCH_DATA.RM_VM_LABLE_VALUE ";
                SQL = SQL + "   = SL_PAY_TYPE_MASTER.SALES_PAY_TYPE_CODE(+) )RMVENDMSTBRANCHPAYTERMSDATA, ";

                SQL = SQL + "(  select ";
                SQL = SQL + "    RM_VM_VENDOR_CODE ,  AD_BR_CODE , ";
                SQL = SQL + "    RM_VM_LABLE_VALUE VENDOR_STATUS   ,RM_VM_LABLE_ID ";
                SQL = SQL + "    from rm_vendor_master_BRANCH_DATA     ";
                SQL = SQL + "    where RM_VM_LABLE_ID ='VENDORBR_STAUS_AI'  ";
                SQL = SQL + "    and AD_BR_CODE='" + Division + "'   )RMVENDMSTBRANCHACTIVEDATA ";


                SQL = SQL + " WHERE "; 
                SQL = SQL + "   RM_VENDOR_MASTER.RM_VM_VENDOR_CODE =";
                SQL = SQL + " RMVENDMSTBRANCHPAYTERMSDATA.RM_VM_VENDOR_CODE";
                SQL = SQL + " AND RM_VENDOR_MASTER.RM_VM_VENDOR_CODE =";
                SQL = SQL + " RMVENDMSTBRANCHACTIVEDATA.RM_VM_VENDOR_CODE";
                SQL = SQL + " AND RMVENDMSTBRANCHACTIVEDATA.VENDOR_STATUS='A' ";
                 
                SQL = SQL + " ORDER BY RM_VENDOR_MASTER.RM_VM_VENDOR_NAME ";
                 
                dtData = clsSQLHelper.GetDataTableByCommand(SQL);
            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return dtData;
        }

        public DataTable FillTrailerView ( )//
        {
            DataTable dtType = new DataTable();
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = "  SELECT   FA_FIXED_ASSET_MASTER.FA_FAM_REF_CODE REF_CODE ,  ";
                SQL = SQL + " FA_FIXED_ASSET_MASTER.FA_FAM_ASSET_CODE CODE , FA_FIXED_ASSET_MASTER.FA_FAM_ASSET_DESCRIPTION NAME,  ";
                SQL = SQL + " FA_FIXED_ASSET_MASTER.FA_FAM_PLATENO  phone,RM_DRIVER_MASTER_DETS.HR_EMP_EMPLOYEE_CODE drcode,HR_EMP_EMPLOYEE_NAME drname  ";
                SQL = SQL + " FROM FA_FIXED_ASSET_MASTER , WS_ASSET_CATEGORY_TYPE,RM_DRIVER_MASTER_DETS,HR_EMPLOYEE_MASTER  ";
                SQL = SQL + " WHERE FA_FIXED_ASSET_MASTER.FA_FAM_VEHICLE_TYPE = WS_ASSET_CATEGORY_TYPE.SL_NO  ";
                SQL = SQL + " AND FA_FIXED_ASSET_MASTER.FA_FAM_ASSET_STATUS ='A'  ";
                SQL = SQL + " AND  RM_DRIVER_MASTER_DETS.HR_EMP_EMPLOYEE_CODE = HR_EMPLOYEE_MASTER.HR_EMP_EMPLOYEE_CODE (+)"; 
                SQL = SQL + " AND   FA_FIXED_ASSET_MASTER.FA_FAM_ASSET_CODE= RM_DRIVER_MASTER_DETS.FA_FAM_ASSET_CODE (+) ";
                SQL = SQL + " AND  FA_FIXED_ASSET_MASTER.FA_FAM_VEHICLE_TYPE   ";
                SQL = SQL + " IN  (  SELECT RM_IP_PARAMETER_VALUE FROM   RM_DEFUALTS_DRIVER_TRAILER ";
                SQL = SQL + " WHERE RM_IP_PARAMETER_DESC ='TRAILER_TYPE_CODE' ) ";

                dtType = clsSQLHelper.GetDataTableByCommand(SQL);
            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }

        public DataTable FillDriverAccountView ( )//
        {
            DataTable dtType = new DataTable();
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT HR_EMPLOYEE_MASTER.HR_EMP_EMPLOYEE_CODE CODE, HR_EMPLOYEE_MASTER.HR_EMP_EMPLOYEE_NAME NAME, ";
                SQL = SQL + " HR_EMPLOYEE_MASTER.HR_EMP_TELNO TEL_NO, HR_EMPLOYEE_MASTER.HR_EMP_MOBILENO MOBILE_NO ";
                SQL = SQL + " FROM HR_EMPLOYEE_MASTER  ";
                SQL = SQL + " WHERE  HR_EMP_STATUS ='A' AND  HR_DM_DESIGNATION_CODE  ";
                SQL = SQL + " IN  (  SELECT RM_IP_PARAMETER_VALUE FROM   RM_DEFUALTS_DRIVER_TRAILER ";
                SQL = SQL + " WHERE RM_IP_PARAMETER_DESC ='TRAILER_DESIG_CODE' ) ";

                dtType = clsSQLHelper.GetDataTableByCommand(SQL);
            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }
         
        public DataTable FecthViewEntry ( string EntryNo, string id )
        {
            DataTable dt = new DataTable();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();
                SQL = "SELECT   ";
                SQL = SQL + " RM_RT_TOKEN_NO,AD_FIN_FINYRID,  ";
                SQL = SQL + "  RM_RT_TOKEN_DATE,RM_RT_TOKEN_DATE_TIME,  ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE,CASE WHEN RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE='16' THEN 'OTHER ITEMS' ELSE  RM_RMM_RM_DESCRIPTION  END AS RM_DESCRIPTION, ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE,RM_VM_VENDOR_NAME,  ";
                SQL = SQL + "  FA_FAM_ASSET_CODE,RM_RT_VEHICLE_DESCRIPTION,  ";
                SQL = SQL + "  RM_RT_DRIVER_CODE,RM_RT_DRIVER_NAME,RM_RT_CREATEDBY,RM_RT_CREATEDDATE,RM_RT_UPDATEDBY,  ";
                SQL = SQL + "  RM_RT_UPDATEDDATE,RM_MRM_RECEIPT_NO,RM_MRM_FINYRID,RM_RT_STATUS ,   ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.AD_BR_CODE,AD_BR_NAME,RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE,SALES_STN_STATION_NAME         ";
                SQL = SQL + "  FROM       ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST,rm_vendor_master,sl_station_master,AD_BRANCH_MASTER  ,RM_RAWMATERIAL_MASTER     ";
                SQL = SQL + "  WHERE RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE=rm_vendor_master.RM_VM_VENDOR_CODE     ";
                SQL = SQL + "        AND RM_RECEPIT_TOKEN_MST.RM_RMM_RM_CODE=RM_RAWMATERIAL_MASTER.RM_RMM_RM_CODE (+) ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE=sl_station_master.SALES_STN_STATION_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.AD_BR_CODE=AD_BRANCH_MASTER.AD_BR_CODE     ";
                SQL = SQL + " and RM_RT_TOKEN_NO='"+EntryNo+"'  ";
                SQL = SQL + " and AD_FIN_FINYRID='"+id+"' ";

                dt = clsSQLHelper.GetDataTableByCommand(SQL);
            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return dt;
        }

        public DataTable FillViewStation (string UserName)
        { 
            DataTable dtReturn = new DataTable();
            try
            {

                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();


                SQL = " SELECT   SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_CODE, SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_NAME, ";
                SQL = SQL + "  SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_CODE CODE  , SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_NAME NAME  , ";
                SQL = SQL + "  SL_STATION_BRANCH_MAPP_DTLS_VW.GL_COSM_ACCOUNT_CODE  ";
                SQL = SQL + " FROM ";
                SQL = SQL + "   SL_STATION_BRANCH_MAPP_DTLS_VW WHERE   ";
                SQL = SQL + "    SALES_STATION_BRANCH_STATUS_AI ='A' and SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_PRODUCTION_STATION ='Y'    ";

                 
                if (UserName != "ADMIN")
                {
                    SQL = SQL + "   AND SL_STATION_BRANCH_MAPP_DTLS_VW.AD_BR_CODE in (select AD_BR_CODE from  ";
                    SQL = SQL + "  AD_USER_GRANTED_BRANCH where AD_UM_USERID = '" + UserName + "')   ";
                }
                if (UserName != "ADMIN")
                {
                    SQL = SQL + "  AND SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_CODE IN ( SELECT     SALES_STN_STATION_CODE FROM ";
                    SQL = SQL + "     WS_GRANTED_STATION_USERS WHERE    AD_UM_USERID   ='" + UserName + "') ";
                }

                 
                SQL = SQL + "  ORDER BY   SL_STATION_BRANCH_MAPP_DTLS_VW.SALES_STN_STATION_NAME     ASC  ";
                 
                dtReturn = clsSQLHelper.GetDataTableByCommand(SQL); 

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtReturn ;

        }
        
        public DataTable FillSearchView (string Status )
        { 
            DataTable dtReturn = new DataTable();
            try
            {

                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = "SELECT   ";
                SQL = SQL + " RM_RT_TOKEN_NO,AD_FIN_FINYRID,  ";
                SQL = SQL + "  RM_RT_TOKEN_DATE,RM_RT_TOKEN_DATE_TIME,  ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE,RM_VM_VENDOR_NAME,  ";
                SQL = SQL + "  FA_FAM_ASSET_CODE,RM_RT_VEHICLE_DESCRIPTION,  ";
                SQL = SQL + "  RM_RT_DRIVER_CODE,RM_RT_DRIVER_NAME,RM_RT_CREATEDBY,RM_RT_CREATEDDATE,RM_RT_UPDATEDBY,  ";
                SQL = SQL + "  RM_RT_UPDATEDDATE,RM_MRM_RECEIPT_NO,RM_MRM_FINYRID,RM_RT_STATUS ,   ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST.AD_BR_CODE,AD_BR_NAME,RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE,SALES_STN_STATION_NAME         ";
                SQL = SQL + "  FROM       ";
                SQL = SQL + "  RM_RECEPIT_TOKEN_MST,rm_vendor_master,sl_station_master,AD_BRANCH_MASTER      ";
                SQL = SQL + "  WHERE RM_RECEPIT_TOKEN_MST.RM_VM_VENDOR_CODE=rm_vendor_master.RM_VM_VENDOR_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.SALES_STN_STATION_CODE=sl_station_master.SALES_STN_STATION_CODE     ";
                SQL = SQL + "  and RM_RECEPIT_TOKEN_MST.AD_BR_CODE=AD_BRANCH_MASTER.AD_BR_CODE";
                SQL = SQL + "  and RM_RT_STATUS='"+Status+"'";
                 
                dtReturn = clsSQLHelper.GetDataTableByCommand(SQL); 

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtReturn ;

        }



        #region "RM Lookup"

        public DataTable FillView( )
        {

            DataTable dtType = new DataTable();
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();


                SQL = " SELECT RM_RAWMATERIAL_MASTER.RM_RMM_RM_CODE Code , RM_RAWMATERIAL_MASTER.RM_RMM_RM_DESCRIPTION Name    ";
                SQL = SQL + " FROM RM_RAWMATERIAL_MASTER , RM_UOM_MASTER  ";
                SQL = SQL + "  where RM_RAWMATERIAL_MASTER.RM_UM_UOM_CODE  =  RM_UOM_MASTER.RM_UM_UOM_CODE (+)";
                SQL = SQL + " AND RM_RAWMATERIAL_MASTER.RM_RMM_RM_STATUS ='A'";
                SQL = SQL + " AND RM_RMM_RM_TYPE NOT IN  (  'WIRE MESH','TOLL','ICE')  "; 
                SQL = SQL + "  UNION ALL ";
                SQL = SQL + "    SELECT ";
                SQL = SQL + "        RM_WTM_RM_CODE Code , RM_WTM_RM_NAME Name   ";
                SQL = SQL + "    FROM ";
                SQL = SQL + "        RM_WEIGHT_TRACK_MATERIAL_MAST   ";
                SQL = SQL + "    WHERE  ";
                SQL = SQL + "        RM_WTM_RM_CODE='16'  ";
                SQL = SQL + "    ORDER BY  ";
                SQL = SQL + "        Code ASC  ";
                 




                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }


        #endregion



        public DataTable HideUnpprovlControl ( object mngrclassobj, string sItemId )
        {
            DataTable dtHideApprovlControl = new DataTable();

            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                SQL = "";
                SQL = " SELECT  count(*) cnt";
                SQL = SQL + "   FROM   ad_mail_approval_users";
                SQL = SQL + "  WHERE  ";
                SQL = SQL + "    ad_mail_approval_users.ad_um_userid = '" + mngrclass.UserName + "'";
                SQL = SQL + "    AND  ad_mail_approval_users.AD_AF_ID  = '" + sItemId + "'";

                dtHideApprovlControl = clsSQLHelper.GetDataTableByCommand(SQL);
            }

            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtHideApprovlControl;
        }


        #endregion
    }

    //------------------- ENTITY ---------------------------------------------------------- SHOULD WRITE THE CODE BELOW -JOMY /////

    #region "ENTITY" 

    public class RMWeighbridgeTokenEntryEntity
    {
        public RMWeighbridgeTokenEntryEntity ( )
        {
            //
            // TODO: Add constructor logic here
            //
        }

         public string TokenNo { get; set; }

         public string DriverCode { get; set; }
         public string DriverName { get; set; }
         public string RMCode { get; set; }
         public string TruckCode { get; set; }
         public string TruckName { get; set; }
         public string VendorCode { get; set; }
         public string BranchCode { get; set; }
         public string StationCode { get; set; }
         public string CreatedBy { get; set; }
         public DateTime TokenDate { get; set; }
         public DateTime TokenTime { get; set; }

    }
 
    public class RMWeighbridgeTokenEntry
    {
        public string fromdate { get; set; }
        public string todate { get; set; }
        public string TruckNo { get; set; }
        public string TokenNo { get; set; }
        public string ProductAppStatus { get; set; }
        public string Branch { get; set; }
        public string Station { get; set; }

    }
    #endregion 

    //------------------- ENTITY ---------------------------------------------------------- SHOULD WRITE THE CODE BELOW -JOMY /////
}