using System;
using System.Data; using AccosoftUtilities;   using AccosoftLogWriter;  using AccosoftNineteenCDL;   
using System.Configuration;
using System.Linq;
using System.Web;
 
using System.Xml.Linq;
using Oracle.ManagedDataAccess.Client; using Oracle.ManagedDataAccess.Types;
using System.Collections;

/// <summary>
/// Summary description for SourceMaster
/// </summary>
/// 

namespace AccosoftRML.Busiess_Logic.RawMaterial
{
 
    public class SourceMasterLogic
    {
        static string sConString = Utilities.cnnstr;
        //   string scon = sConString;

        OracleConnection ocConn = new OracleConnection(sConString.ToString()); 
    

        
        //OracleConnection ocConn = new OracleConnection(System.Configuration.ConfigurationManager.ConnectionStrings["accoSoftConnection"].ToString());
        ArrayList sSQLArray = new ArrayList();
        String SQL = string.Empty;

        public SourceMasterLogic()
        {
            //
            // TODO: Add constructor logic here
            //
        }
        public DataTable FetchData()
        {
            DataTable dtType = new DataTable();
            try
            {



                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT RM_SM_SOURCE_CODE CODE, RM_SM_SOURCE_DESC  NAME FROM RM_SOURCE_MASTER";


                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }
        
        public DataTable FillStation()
        {
            DataTable dtStation = new DataTable();
            try
            {



                SqlHelper clsSQLHelper = new SqlHelper();

                
                SQL = "SELECT  ";
                SQL = SQL + "SALES_STN_STATION_CODE,SALES_STN_STATION_NAME ";
                SQL = SQL + "FROM SL_STATION_MASTER  ";
                SQL = SQL + " WHERE SALES_STN_DELETESTATUS=0  and SALES_RAW_MATERIAL_STATION ='Y'  order by SALES_STN_STATION_NAME asc";

                dtStation = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {

            }
            return dtStation;
        }

        public DataTable FillView()
        {
            DataTable dtType = new DataTable();
            try
            {



                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT RM_SM_SOURCE_CODE CODE, RM_SM_SOURCE_DESC  NAME,nvl(SALES_STN_STATION_CODE,0) SALES_STN_STATION_CODE FROM RM_SOURCE_MASTER";


                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                
            }
            return dtType;
        }


        #region "DML"

        public string InsertSql(string sCompanyTypeCode, string sCompanyTypeName,string station, bool bDocAutogenerated , object mngrclassobj)
        {
            string sRetun = string.Empty;
            //int nRecordsAffected = 0; 
            try
            {

                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                sSQLArray.Clear();

                SQL = "  ";

                SQL = " INSERT INTO RM_SOURCE_MASTER (";
                SQL = SQL + "    RM_SM_SOURCE_CODE, RM_SM_SOURCE_DESC, AD_CM_COMPANY_CODE, ";
                SQL = SQL + "    RM_SM_CREATEDBY, RM_SM_CREATEDDATE, RM_SM_UPDATEDBY, ";
                SQL = SQL + "    RM_SM_UPDATEDDATE, RM_SM_DELETESTATUS,SALES_STN_STATION_CODE) ";


                SQL = SQL + " VALUES ('" + sCompanyTypeCode + "'  ,'" + sCompanyTypeName + "','" + mngrclass.CompanyCode + "' ,";
                SQL = SQL + " '" + mngrclass.UserName + "' ,'" + DateTime.Now.ToString("dd-MMM-yyyy") + "', '',";
                SQL = SQL + "''  ,0,'"+ station + "' )"; 
                 
                sSQLArray.Add(SQL);


                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMSM", sCompanyTypeCode, bDocAutogenerated, Environment.MachineName, "I", sSQLArray);



            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }

        public string UpdateSql(string sCode, string sName,string Station, object mngrclassobj) 
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;
                sSQLArray.Clear();
                SQL = "  ";


                SQL = " UPDATE    RM_SOURCE_MASTER  SET  RM_SM_SOURCE_DESC = '" + sName + "',";


                SQL = SQL + "  RM_SM_UPDATEDDATE ='" + DateTime.Now.ToString("dd-MMM-yyyy") + "', ";
                SQL = SQL + " RM_SM_UPDATEDBY  ='" + mngrclass.UserName + "',";
                SQL = SQL + " SALES_STN_STATION_CODE  ='" + Station + "'";


                SQL = SQL + " WHERE RM_SM_SOURCE_CODE ='" + sCode + "'";




                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID , mngrclass.CompanyCode, DateTime.Now, "RMSM", sCode, false, Environment.MachineName, "U", sSQLArray);


            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }

            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }

        public string DeleteSql(string sCompanyTypeCode, object mngrclassobj)
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                if (DeleteCheck(sCompanyTypeCode) != "CONTINUE")
                {
                    return "Child Record Exists.";
                }
                sSQLArray.Clear();

                SQL = " DELETE FROM     RM_SOURCE_MASTER    ";

                SQL = SQL + " WHERE RM_SM_SOURCE_CODE ='" + sCompanyTypeCode + "'";


                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMSM", sCompanyTypeCode, false, Environment.MachineName, "D", sSQLArray);


            }
            catch (Exception ex)
            {

            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }



        private string DeleteCheck(string Code)
        {
            DataSet dsCnt = new DataSet();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                // SQL Statment for fethiing the  opening 



                SQL = " SELECT   count(*) CNT  FROM RM_PO_DETAILS ";
                SQL = SQL + " WHERE  RM_SM_SOURCE_CODE ='" + Code + "'";


                dsCnt = clsSQLHelper.GetDataset(SQL);

                if (System.Convert.ToInt16(dsCnt.Tables[0].Rows[0].ItemArray[0]) > 0)
                {
                    return "Code referernce exists ";
                }


            }
            catch (Exception ex)
            {
                return System.Convert.ToString(ex.Message);
            }
            return "CONTINUE";
        }




   

        #endregion 

    }

}