using System;
using System.Data;
using AccosoftUtilities;
using AccosoftLogWriter;
using AccosoftNineteenCDL;
using System.Configuration;
using System.Linq;
using System.Web;

using System.Xml.Linq;
using Oracle.ManagedDataAccess.Client; using Oracle.ManagedDataAccess.Types;
using System.Collections;

//----------------------------------------------------------------

//CREATED BY : JISHNU

//CREATED ON : 22-03-2019

//CREATED PAGE DETAILS : SUPPLIER ORIGIN COUNTRY MASTER LOGIC

//----------------------------------------------------------------

namespace AccosoftRML.Busiess_Logic.RawMaterial
{
   public class SupplierOriginCountryMasterLogic
    {
        static string sConString = Utilities.cnnstr;
        OracleConnection ocConn = new OracleConnection(sConString.ToString());
        ArrayList sSQLArray = new ArrayList();
        String SQL = string.Empty;

        #region " FUNCTION FOR FETCHING "

        public DataTable FetchData()
        {
            DataTable dtType = new DataTable();
            try
            {

                SQL = string.Empty;

                SqlHelper clsSQLHelper = new SqlHelper();

              
                SQL = "  SELECT RM_CO_ORIGIN_CODE CODE, RM_CO_ORIGIN_DESC  NAME,RM_CO_ALPHA_3_CODE ALPHA_3,RM_CO_NUMERIC_CODE RM_CODE  ";
                SQL = SQL + " FROM RM_COUNTRY_ORIGIN_MASTER";

                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return dtType;

        }

        #endregion

        #region " DML STATEMENTS "

        public string InsertSql(string sCode,string sAlphaCode,string sNumeric, string sName, bool bDocAutogenerated, object mngrclassobj)
        {
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;
                
                sSQLArray.Clear();

                SQL = " INSERT INTO RM_COUNTRY_ORIGIN_MASTER (";
                SQL = SQL + " RM_CO_ORIGIN_CODE,RM_CO_ALPHA_3_CODE,RM_CO_NUMERIC_CODE, RM_CO_ORIGIN_DESC, AD_CM_COMPANY_CODE, ";
                SQL = SQL + " RM_CO_ORIGIN_CREATEDBY, RM_CO_ORIGIN_CREATEDDATE, RM_CO_ORIGIN_UPDATEDBY, ";
                SQL = SQL + " RM_CO_ORIGIN_UPDATEDDATE, RM_CO_ORIGIN_DELETESTATUS) ";
                SQL = SQL + " VALUES ('" + sCode + "'  ,'" + sAlphaCode + "'  ,'" + sNumeric + "'  ,'" + sName + "'  ,'" + mngrclass.CompanyCode + "' ,";
                SQL = SQL + " '" + mngrclass.UserName + "' ,'" + DateTime.Now.ToString("dd-MMM-yyyy") + "', '',";
                SQL = SQL + "''  ,0 )";

                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMCUNTRYORGN", sCode, bDocAutogenerated, Environment.MachineName, "I", sSQLArray);
            }
            catch (Exception ex)
            {

            }

            return sRetun;
        }

        public string UpdateSql(string sCode, string sName, object mngrclassobj)
        {
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();
                SessionManager mngrclass = (SessionManager)mngrclassobj;

                sSQLArray.Clear();
                SQL = "  ";

                SQL = " UPDATE RM_COUNTRY_ORIGIN_MASTER  SET  RM_CO_ORIGIN_DESC = '" + sName + "',  ";
                SQL = SQL + "  RM_CO_ORIGIN_UPDATEDDATE ='" + DateTime.Now.ToString("dd-MMM-yyyy") + "', ";
                SQL = SQL + " RM_CO_ORIGIN_UPDATEDBY  ='" + mngrclass.UserName + "'";

                SQL = SQL + " WHERE RM_CO_ORIGIN_CODE ='" + sCode + "'";

                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMCUNTRYORGN", sCode, false, Environment.MachineName, "U", sSQLArray);
            }
            catch (Exception ex)
            {

            }
            return sRetun;
        }

        public string DeleteSql(string sCode, object mngrclassobj)
        {
               string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                if (DeleteCheck(sCode) != "CONTINUE")
                {
                    return "Child Record Exists.";
                }

                sSQLArray.Clear();


                SQL = " DELETE FROM     RM_COUNTRY_ORIGIN_MASTER    ";

                SQL = SQL + " WHERE RM_CO_ORIGIN_CODE ='" + sCode + "'";


                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMCUNTRYORGN", sCode, false, Environment.MachineName, "D", sSQLArray);
            }
            catch (Exception ex)
            {

            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }

        private string DeleteCheck(string Code)
        {
            DataSet dsCnt = new DataSet();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT  count(*) CNT   FROM  RM_VENDOR_MASTER";
                SQL = SQL + " WHERE RM_CO_ORIGIN_CODE='" + Code + "'";

                dsCnt = clsSQLHelper.GetDataset(SQL);

                if (System.Convert.ToInt16(dsCnt.Tables[0].Rows[0].ItemArray[0]) > 0)
                {
                    return "Code referernce exists in rawmaterial or Item master";
                }
            }
            catch (Exception ex)
            {
                return System.Convert.ToString(ex.Message);
            }

            return "CONTINUE";
        }

        #endregion
    }
}
