using System;
using System.Data;
using AccosoftUtilities;
using AccosoftLogWriter;
using AccosoftNineteenCDL;
using System.Configuration;
using System.Linq;
using System.Web;

using System.Xml.Linq;
using Oracle.ManagedDataAccess.Client; using Oracle.ManagedDataAccess.Types;
using System.Collections;

namespace AccosoftRML.Busiess_Logic.RawMaterial
{
    public class TollLocationMasterLogic
    {
        static string sConString = Utilities.cnnstr;
        //   string scon = sConString;

        OracleConnection ocConn = new OracleConnection(sConString.ToString());



        //OracleConnection ocConn = new OracleConnection(System.Configuration.ConfigurationManager.ConnectionStrings["accoSoftConnection"].ToString());
        ArrayList sSQLArray = new ArrayList();
        String SQL = string.Empty;

        public TollLocationMasterLogic()
        {
            //
            // TODO: Add constructor logic here
            //
        }
        public DataTable FetchData()
        {
            DataTable dtType = new DataTable();
            try
            {

                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT RM_TL_LOCATION_CODE CODE, RM_TL_LOCATION_DESC  NAME FROM RM_RECEPIT_TOLL_LOCATION_MAST";
                
                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }

        public DataTable FillView()
        {
            DataTable dtType = new DataTable();
            try
            {

                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT RM_TL_LOCATION_CODE CODE, RM_TL_LOCATION_DESC  NAME FROM RM_RECEPIT_TOLL_LOCATION_MAST";


                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {

            }
            return dtType;
        }


        #region "DML"

        public string InsertSql(string sCompanyTypeCode, string sCompanyTypeName, bool bDocAutogenerated, object mngrclassobj)
        {
            string sRetun = string.Empty;
            //int nRecordsAffected = 0; 
            try
            {

                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                sSQLArray.Clear();

                SQL = "  ";

                SQL = " INSERT INTO RM_RECEPIT_TOLL_LOCATION_MAST (";
                SQL = SQL + "    RM_TL_LOCATION_CODE, RM_TL_LOCATION_DESC, AD_CM_COMPANY_CODE, ";
                SQL = SQL + "    RM_TL_CREATEDBY, RM_TL_CREATEDDATE, RM_TL_UPDATEDBY, ";
                SQL = SQL + "    RM_TL_UPDATEDDATE, RM_TL_DELETESTATUS) ";


                SQL = SQL + " VALUES ('" + sCompanyTypeCode + "'  ,'" + sCompanyTypeName + "','" + mngrclass.CompanyCode + "' ,";
                SQL = SQL + " '" + mngrclass.UserName + "' ,'" + DateTime.Now.ToString("dd-MMM-yyyy") + "', '',";
                SQL = SQL + "''  ,0)";

                sSQLArray.Add(SQL);


                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMTLLCMST", sCompanyTypeCode, bDocAutogenerated, Environment.MachineName, "I", sSQLArray);



            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }

        public string UpdateSql(string sCode, string sName, object mngrclassobj)
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;
                sSQLArray.Clear();
                SQL = "  ";


                SQL = " UPDATE    RM_RECEPIT_TOLL_LOCATION_MAST  SET  RM_TL_LOCATION_DESC = '" + sName + "',";


                SQL = SQL + "  RM_TL_UPDATEDDATE ='" + DateTime.Now.ToString("dd-MMM-yyyy") + "', ";
                SQL = SQL + " RM_TL_UPDATEDBY  ='" + mngrclass.UserName + "'";


                SQL = SQL + " WHERE RM_TL_LOCATION_CODE ='" + sCode + "'";




                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMTLLCMST", sCode, false, Environment.MachineName, "U", sSQLArray);


            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }

            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }

        public string DeleteSql(string sCompanyTypeCode, object mngrclassobj)
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                if (DeleteCheck(sCompanyTypeCode) != "CONTINUE")
                {
                    return "Child Record Exists.";
                }
                sSQLArray.Clear();

                SQL = " DELETE FROM     RM_RECEPIT_TOLL_LOCATION_MAST    ";

                SQL = SQL + " WHERE RM_TL_LOCATION_CODE ='" + sCompanyTypeCode + "'";


                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMTLLCMST", sCompanyTypeCode, false, Environment.MachineName, "D", sSQLArray);


            }
            catch (Exception ex)
            {

            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }
               
        private string DeleteCheck(string Code)
        {
            DataSet dsCnt = new DataSet();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                // SQL Statment for fethiing the  opening 



                SQL = " SELECT   count(*) CNT  FROM RM_RECEPIT_TOLL ";
                SQL = SQL + " WHERE  RM_TL_LOCATION_CODE ='" + Code + "'";


                dsCnt = clsSQLHelper.GetDataset(SQL);

                if (System.Convert.ToInt16(dsCnt.Tables[0].Rows[0].ItemArray[0]) > 0)
                {
                    return "Code referernce exists ";
                }


            }
            catch (Exception ex)
            {
                return System.Convert.ToString(ex.Message);
            }
            return "CONTINUE";
        }

        #endregion

    }
}
