using System;
using System.Data;
using AccosoftUtilities;
using AccosoftLogWriter;
using AccosoftNineteenCDL;
using System.Configuration;
using System.Linq;
using System.Web;

using System.Xml.Linq;
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;
using System.Collections;

namespace AccosoftRML.Busiess_Logic.RawMaterial
{
    public class UOMMasterShaluLogics
     {

        static string sConString = Utilities.cnnstr;
        //   string scon = sConString;

        OracleConnection ocConn = new OracleConnection(sConString.ToString());




        // OracleConnection ocConn = new OracleConnection(System.Configuration.ConfigurationManager.ConnectionStrings["accoSoftConnection"].ToString());
        ArrayList sSQLArray = new ArrayList();
        String SQL = string.Empty;

        public UOMMasterShaluLogics( )
        {
            //
            // TODO: Add constructor logic here
            //
        }

        #region "Fetch"

        public DataTable FetchData ( )
        {
            DataTable dtType = new DataTable();
            try
            {

                SQL = string.Empty;

                SqlHelper clsSQLHelper = new SqlHelper();

                //SQL = "  SELECT RM_UM_UOM_CODE CODE, RM_UM_UOM_DESC  NAME, nvl(RM_UOM_CAT_CODE,'NA') Category FROM RM_UOM_MASTER ";
                SQL = "SELECT RM_UM_UOM_CODE        CODE, ";
                SQL = SQL + "       RM_UM_UOM_DESC        NAME, ";
                SQL = SQL + "       RM_UOM_MASTER.RM_UOM_CAT_CODE, ";
                SQL = SQL + "       RM_UOM_CAT_NAME, ";
                SQL = SQL + "       RM_UM_READYMIX_YN     READYMIX_CODE, ";
                SQL = SQL + "       READYMIX.NAME         READYMIX_NAME, ";
                SQL = SQL + "       RM_UM_BLOCK_YN        BLOCK_CODE, ";
                SQL = SQL + "       BLOCK.NAME            BLOCK_NAME, ";
                SQL = SQL + "       RM_UM_PRECAST_YN      PRECAST_CODE, ";
                SQL = SQL + "       PRECAST.NAME          PRECAST_NAME ";
                SQL = SQL + "  FROM RM_UOM_MASTER, ";
                SQL = SQL + "       RM_UOM_CATEGORY_MASTER, ";
                SQL = SQL + "       RM_UOM_BRANCH_YN_VW  READYMIX, ";
                SQL = SQL + "       RM_UOM_BRANCH_YN_VW  BLOCK, ";
                SQL = SQL + "       RM_UOM_BRANCH_YN_VW  PRECAST ";
                SQL = SQL + " WHERE     RM_UOM_MASTER.RM_UOM_CAT_CODE =  RM_UOM_CATEGORY_MASTER.RM_UOM_CAT_CODE(+) ";
                SQL = SQL + "       AND RM_UOM_MASTER.RM_UM_READYMIX_YN = READYMIX.CODE ";
                SQL = SQL + "       AND RM_UOM_MASTER.RM_UM_BLOCK_YN = BLOCK.CODE ";
                SQL = SQL + "       AND RM_UOM_MASTER.RM_UM_PRECAST_YN = PRECAST.CODE ";
             ////   SQL = SQL + "       ORDER BY RM_UM_UOM_CODE ASC ";

                dtType = clsSQLHelper.GetDataTableByCommand(SQL);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return dtType;

        }

        #endregion

        #region " DML"

        public string InsertSql ( string sCompanyTypeCode, string sCompanyTypeName, string Category, string ReadyMixYN, string BlockYN, string PrecastYN, bool bDocAutogenerated, object mngrclassobj )
        {
            string sRetun = string.Empty;
            //int nRecordsAffected = 0; 
            try
            {

                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;


                sSQLArray.Clear();

                SQL = "  ";


                SQL = " INSERT INTO RM_UOM_MASTER (";
                SQL = SQL + " RM_UM_UOM_CODE, RM_UM_UOM_DESC, AD_CM_COMPANY_CODE, ";
                SQL = SQL + " RM_UM_CREATEDBY, RM_UM_CREATEDDATE, RM_UM_UPDATEDBY, ";
                SQL = SQL + " RM_UM_UPDATEDDATE, RM_UM_DELETESTATUS,RM_UOM_CAT_CODE, ";
                SQL = SQL + " RM_UM_READYMIX_YN, RM_UM_BLOCK_YN,RM_UM_PRECAST_YN) ";
                SQL = SQL + " VALUES ('" + sCompanyTypeCode + "'  ,'" + sCompanyTypeName + "'  ,'" + mngrclass.CompanyCode + "' ,";
                SQL = SQL + " '" + mngrclass.UserName + "' ,'" + DateTime.Now.ToString("dd-MMM-yyyy") + "', '',";
                SQL = SQL + " ''  ,0 ,'" + Category + "',";
                SQL = SQL + " '" + ReadyMixYN + "' ,'" + BlockYN + "' ,'" + PrecastYN + "')";


                sSQLArray.Add(SQL);


                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMUM", sCompanyTypeCode, bDocAutogenerated, Environment.MachineName, "I", sSQLArray);



            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }
            finally
            {
                // ocConn.Close();
                // ocConn.Dispose();
            }
            return sRetun;
        }

        public string UpdateSql ( string sCode, string sName, string scat, string ReadyMix, string Block, string Precast, object mngrclassobj )
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();
                SessionManager mngrclass = (SessionManager)mngrclassobj;

                sSQLArray.Clear();
                SQL = "  ";

                SQL = " UPDATE    RM_UOM_MASTER  SET  RM_UM_UOM_DESC = '" + sName + "',  ";
                SQL = SQL + "RM_UOM_CAT_CODE = '" + scat + "',";
                SQL = SQL + "RM_UM_READYMIX_YN = '" + ReadyMix + "',";
                SQL = SQL + "RM_UM_BLOCK_YN = '" + Block + "',";
                SQL = SQL + "RM_UM_PRECAST_YN = '" + Precast + "',";
                SQL = SQL + "  RM_UM_UPDATEDDATE ='" + DateTime.Now.ToString("dd-MMM-yyyy") + "', ";
                SQL = SQL + " RM_UM_UPDATEDBY  ='" + mngrclass.UserName + "'";

                SQL = SQL + " WHERE RM_UM_UOM_CODE ='" + sCode + "'";



                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMUM", sCode, false, Environment.MachineName, "U", sSQLArray);


            }
            catch (Exception ex)
            {
                sRetun = System.Convert.ToString(ex.Message);
            }

            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }

        public string DeleteSql ( string sCompanyTypeCode, object mngrclassobj )
        {
            // int nRecordsAffected = 0;
            string sRetun = string.Empty;
            try
            {
                OracleHelper oTrns = new OracleHelper();

                SessionManager mngrclass = (SessionManager)mngrclassobj;

                if (DeleteCheck(sCompanyTypeCode) != "CONTINUE")
                {
                    return "Child Record Exists.";
                }
                sSQLArray.Clear();




                SQL = " DELETE FROM     RM_UOM_MASTER    ";

                SQL = SQL + " WHERE RM_UM_UOM_CODE ='" + sCompanyTypeCode + "'";


                sSQLArray.Add(SQL);

                sRetun = oTrns.SetTrans(mngrclass.UserName, mngrclass.FinYearID, mngrclass.CompanyCode, DateTime.Now, "RMUM", sCompanyTypeCode, false, Environment.MachineName, "D", sSQLArray);


            }
            catch (Exception ex)
            {

            }
            finally
            {
                //ocConn.Close();
                //ocConn.Dispose();
            }
            return sRetun;
        }

        private string DeleteCheck ( string Code )
        {
            DataSet dsCnt = new DataSet();
            try
            {
                SqlHelper clsSQLHelper = new SqlHelper();

                // SQL Statment for fethiing the  opening 


                SQL = " SELECT  count(*) CNT   FROM RM_UOM_CHECK ";
                SQL = SQL + " WHERE RM_UM_UOM_CODE='" + Code + "'";



                dsCnt = clsSQLHelper.GetDataset(SQL);

                if (System.Convert.ToInt16(dsCnt.Tables[0].Rows[0].ItemArray[0]) > 0)
                {
                    return "Code referernce exists in rawmaterial or Item master";
                }


            }
            catch (Exception ex)
            {
                return System.Convert.ToString(ex.Message);
            }
            return "CONTINUE";
        }

        #endregion 

        #region "FillCombo"

        public DataSet fillcombo ( )
        {
            DataSet dsfill = new DataSet();
            DataTable dtfill = new DataTable();
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();
                SQL = " SELECT RM_UOM_CAT_CODE CAT_COE, RM_UOM_CAT_NAME  CATE_NAME   FROM  RM_UOM_CATEGORY_MASTER order by RM_UOM_CAT_SORT_ID desc ";
                dtfill = clsSQLHelper.GetDataTableByCommand(SQL);
                dsfill.Tables.Add(dtfill);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return dsfill;
        }

        public DataSet fillBranchYN ( )
        {
            DataSet dsfill = new DataSet();
            DataTable dtfill = new DataTable();
            try
            {
                SQL = string.Empty;
                SqlHelper clsSQLHelper = new SqlHelper();

                SQL = " SELECT CODE, NAME FROM RM_UOM_BRANCH_YN_VW ";

                dtfill = clsSQLHelper.GetDataTableByCommand(SQL);
                dsfill.Tables.Add(dtfill);

            }
            catch (Exception ex)
            {
                ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
                objLogWriter.WriteLog(ex);
            }
            return dsfill;
        }

        //public DataSet fillReadyMix ( )
        //{
        //    DataSet dsfill = new DataSet();
        //    DataTable dtfill = new DataTable();
        //    try
        //    {
        //        SQL = string.Empty;
        //        SqlHelper clsSQLHelper = new SqlHelper();
        //        SQL = " SELECT CODE READYMIX_CODE, NAME READYMIX_NAME FROM RM_UOM_BRANCH_YN_VW ";
        //        dtfill = clsSQLHelper.GetDataTableByCommand(SQL);
        //        dsfill.Tables.Add(dtfill);

        //    }
        //    catch (Exception ex)
        //    {
        //        ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
        //        objLogWriter.WriteLog(ex);
        //    }
        //    return dsfill;
        //}

        //public DataSet fillBlock ( )
        //{
        //    DataSet dsfill = new DataSet();
        //    DataTable dtfill = new DataTable();
        //    try
        //    {
        //        SQL = string.Empty;
        //        SqlHelper clsSQLHelper = new SqlHelper();
        //        SQL = " SELECT CODE BLOCK_CODE, NAME BLOCK_NAME FROM RM_UOM_BRANCH_YN_VW ";
        //        dtfill = clsSQLHelper.GetDataTableByCommand(SQL);
        //        dsfill.Tables.Add(dtfill);

        //    }
        //    catch (Exception ex)
        //    {
        //        ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
        //        objLogWriter.WriteLog(ex);
        //    }
        //    return dsfill;
        //}

        //public DataSet fillPrecast ( )
        //{
        //    DataSet dsfill = new DataSet();
        //    DataTable dtfill = new DataTable();
        //    try
        //    {
        //        SQL = string.Empty;
        //        SqlHelper clsSQLHelper = new SqlHelper();
        //        SQL = " SELECT CODE PRECAST_CODE, NAME PRECAST_NAME FROM RM_UOM_BRANCH_YN_VW ";
        //        dtfill = clsSQLHelper.GetDataTableByCommand(SQL);
        //        dsfill.Tables.Add(dtfill);

        //    }
        //    catch (Exception ex)
        //    {
        //        ExceptionLogWriter objLogWriter = new ExceptionLogWriter();
        //        objLogWriter.WriteLog(ex);
        //    }
        //    return dsfill;
        //}

        #endregion 
    }
}
