using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AccosoftRML.BaseEntity
{
    public class BaseEntity
    {
        public string Code
        {
            get;
            set;
        }

        public string CrudMode
        {
            get;
            set;
        }


        public string UserName
        {
            get;
            set;
        }
        public DateTime CreatedDate
        {
            get;
            set;
        }

        public DateTime UpdatedDate
        {
            get;
            set;
        }
        public int FinYearID
        {
            get;
            set;
        }

        public string Companycode
        {
            get;
            set;
        }
        public string BranchCode
        {
            get;
            set;
        }
        
        public string ModuleItemID
        {
            get;
            set;
        }

        public string Verified
        {
            get;
            set;
        }

        public string VerifiedBy
        {
            get;
            set;
        }

        public string Approved
        {
            get;
            set;
        }

        public string ApprovedBy
        {
            get;
            set;
        }

        public bool DocAutogenerated
        {
            get;
            set;
        }

        public string MachineName
        {
            get;
            set;
        }
    }
}

